adminUser: admin
adminPassword: admin123

persistence:
  enabled: true
  size: 5Gi

service:
  type: ClusterIP

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: PostgreSQL
      type: postgres
      url: postgres-postgresql.database.svc.cluster.local:5432
      user: admin
      secureJsonData:
        password: admin123
      database: postgres
      jsonData:
        sslmode: "disable"
      isDefault: true
