apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-worker
  namespace: jenkins-workers
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec", "pods/log", "persistentvolumeclaims", "events"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-worker-binding
  namespace: jenkins-workers
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: jenkins
roleRef:
  kind: Role
  name: jenkins-worker
  apiGroup: rbac.authorization.k8s.io
